#!/usr/bin/env python3

import json
import re
import shlex
import sys

data = json.load(sys.stdin)

tool_name = data.get("tool_name")
tool_input = data.get("tool_input", {})
command = tool_input.get("command", "")

if tool_name != "Bash" or "git commit" not in command:
    sys.exit(0)

match = re.search(r'git\s+commit\b.*?\s-m\s+(".*?"|\'.*?\')', command)
if not match:
    sys.exit(0)

raw = match.group(1)

try:
    message = shlex.split(raw)[0]
except Exception:
    message = raw.strip("\"'")

pattern = r"^(feat|fix|docs|refactor|test|chore|ci|build)(\([a-z0-9._/-]+\))?: [a-z0-9].*$"

errors = []

if "\n" in message:
    errors.append("commit message must be a single line")

if len(message) > 72:
    errors.append("commit message must be 72 characters or fewer")

if not re.match(pattern, message):
    errors.append("commit message must follow Conventional Commits")

for forbidden in [
    "Co-authored-by:",
    "Generated by Claude",
    "AI assisted",
    "AI-generated"
]:
    if forbidden.lower() in message.lower():
        errors.append(f'commit message must not contain "{forbidden}"')

if errors:
    print(json.dumps({
        "hookSpecificOutput": {
            "hookEventName": "PreToolUse",
            "permissionDecision": "deny",
            "permissionDecisionReason": "; ".join(errors)
        }
    }))
    sys.exit(0)

sys.exit(0)
